" General
set number	    " Show line numbers
set relativenumber  " Show relative line numbers on the left. These change based upon where your cursor is.
syntax on           " Turn syntax highlighting on
set linebreak	    " Break lines at word (requires Wrap lines)
set showbreak=+++   " Wrap-broken line prefix
set textwidth=120   " Line wrap (number of cols)
set showmatch	    " Highlight matching brace
"set visualbell	    " Use visual bell (no beeping)

set hlsearch	    " Highlight all search results
set smartcase	    " Enable smart-case search
set ignorecase	    " Always case-insensitive
set incsearch	    " Searches for strings incrementally
 
set autoindent	    " Auto-indent new lines
set cursorline      " Highlight current cursor line
" set cursorcolumn    " Highlight current cursor column
set cindent         " Use 'C' style program indenting
set noexpandtab     " Do not use spaces instesd of tabs
set expandtab      " Use spaces instead of tabs
set shiftwidth=4    " Number of auto-indent spaces
set smartindent	    " Enable smart-indent
set smarttab	    " Enable smart-tabs
set tabstop=4	    " Number of spaces per Tab 
"set softtabstop=4  " Number of spaces per Tab 
set foldcolumn=1    " Place a width 1 margin on the left

"" Advanced
set ruler	    " Show row and column ruler information
set colorcolumn=80,120
"" colorscheme slate	" set reasonable color scheme
highlight ColorColumn ctermbg=0 ctermfg=128

set undolevels=1000	        " Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

"" Generated by VimConfig.com
